"""Provide RGB color constants and a colors dictionary with
elements formatted: colors[colorname] = CONSTANT"""

from collections import namedtuple, OrderedDict

Color = namedtuple('RGB','red, green, blue')
colors = {} #dict of colors

class RGB(Color):
    def hex_format(self):
        '''Returns color in hex format'''
        return '#{:02X}{:02X}{:02X}'.format(self.red,self.green,self.blue)

#Color Contants
ALICEBLUE = RGB(94, 97, 100)
ANTIQUEWHITE = RGB(98, 92, 84)
AQUA = RGB(0, 100, 100)
AQUAMARINE = RGB(49, 100, 83)
AZURE = RGB(94, 100, 100)
BANANA = RGB(89, 81, 34)
BEIGE = RGB(96, 96, 86)
BISQUE = RGB(100, 89, 76)
BLACK = RGB(0, 0, 0)
BLANCHEDALMOND = RGB(100, 92, 80)
BLUE = RGB(0, 0, 100)
BLUEVIOLET = RGB(54, 16, 88)
BRICK = RGB(61, 40, 12)
BROWN = RGB(64, 16, 16)
BURLYWOOD = RGB(87, 72, 52)
BURNTSIENNA = RGB(54, 21, 5)
BURNTUMBER = RGB(54, 20, 14)
CADETBLUE = RGB(37, 61, 62)
CADMIUMORANGE = RGB(100, 38, 1)
CADMIUMYELLOW = RGB(100, 60, 7)
CARROT = RGB(92, 56, 12)
CHARTREUSE = RGB(49, 100, 0)
CHOCOLATE = RGB(82, 41, 11)
COBALT = RGB(23, 34, 67)
COBALTGREEN = RGB(23, 56, 25)
COLDGREY = RGB(50, 54, 52)
CORAL = RGB(100, 49, 31)
CORNFLOWERBLUE = RGB(39, 58, 92)
CORNSILK = RGB(100, 97, 86)
CRIMSON = RGB(86, 7, 23)
CYAN = RGB(0, 93, 93)
DARKGOLDENROD = RGB(72, 52, 4)
DARKGRAY = RGB(66, 66, 66)
DARKGREEN = RGB(0, 39, 0)
DARKKHAKI = RGB(74, 71, 41)
DARKOLIVEGREEN = RGB(33, 41, 18)
DARKORANGE = RGB(100, 54, 0)
DARKORCHID = RGB(60, 19, 80)
DARKSALMON = RGB(91, 58, 47)
DARKSEAGREEN = RGB(56, 73, 56)
DARKSLATEBLUE = RGB(28, 23, 54)
DARKSLATEGRAY = RGB(18, 30, 30)
DARKTURQUOISE = RGB(0, 80, 81)
DARKVIOLET = RGB(58, 0, 82)
DEEPPINK = RGB(100, 7, 57)
DEEPSKYBLUE = RGB(0, 74, 100)
DIMGRAY = RGB(41, 41, 41)
DODGERBLUE = RGB(11, 56, 100)
EGGSHELL = RGB(98, 90, 78)
EMERALDGREEN = RGB(0, 78, 34)
FIREBRICK = RGB(69, 13, 13)
FLESH = RGB(100, 49, 25)
FLORALWHITE = RGB(100, 98, 94)
FORESTGREEN = RGB(13, 54, 13)
GAINSBORO = RGB(86, 86, 86)
GHOSTWHITE = RGB(97, 97, 100)
GOLD = RGB(100, 84, 0)
GOLDENROD = RGB(85, 64, 12)
GRAY = RGB(50, 50, 50)
GREEN = RGB(0, 50, 0)
GREENYELLOW = RGB(67, 100, 18)
HONEYDEW = RGB(94, 100, 94)
HOTPINK = RGB(100, 41, 70)
INDIANRED = RGB(80, 36, 36)
INDIGO = RGB(29, 0, 50)
IVORY = RGB(100, 100, 94)
IVORYBLACK = RGB(16, 14, 12)
KHAKI = RGB(94, 90, 54)
LAVENDER = RGB(90, 90, 98)
LAVENDERBLUSH = RGB(100, 94, 96)
LAWNGREEN = RGB(48, 98, 0)
LEMONCHIFFON = RGB(100, 98, 80)
LIGHTBLUE = RGB(67, 84, 90)
LIGHTCORAL = RGB(94, 50, 50)
LIGHTCYAN = RGB(87, 100, 100)
LIGHTGOLDENROD = RGB(100, 92, 54)
LIGHTGOLDENRODYELLOW = RGB(98, 98, 82)
LIGHTGREY = RGB(82, 82, 82)
LIGHTPINK = RGB(100, 71, 75)
LIGHTSALMON = RGB(100, 62, 47)
LIGHTSEAGREEN = RGB(12, 69, 66)
LIGHTSKYBLUE = RGB(52, 80, 98)
LIGHTSLATEBLUE = RGB(51, 43, 100)
LIGHTSLATEGRAY = RGB(46, 53, 60)
LIGHTSTEELBLUE = RGB(69, 76, 87)
LIGHTYELLOW = RGB(100, 100, 87)
LIMEGREEN = RGB(19, 80, 19)
LINEN = RGB(98, 94, 90)
MAGENTA = RGB(100, 0, 100)
MANGANESEBLUE = RGB(1, 65, 61)
MAROON = RGB(50, 0, 0)
MEDIUMORCHID = RGB(72, 33, 82)
MEDIUMPURPLE = RGB(57, 43, 85)
MEDIUMSEAGREEN = RGB(23, 70, 44)
MEDIUMSLATEBLUE = RGB(48, 40, 93)
MEDIUMSPRINGGREEN = RGB(0, 98, 60)
MEDIUMTURQUOISE = RGB(28, 81, 80)
MEDIUMVIOLETRED = RGB(78, 8, 52)
MELON = RGB(89, 65, 41)
MIDNIGHTBLUE = RGB(9, 9, 43)
MINT = RGB(74, 98, 78)
MINTCREAM = RGB(96, 100, 98)
MISTYROSE = RGB(100, 89, 88)
MOCCASIN = RGB(100, 89, 70)
NAVAJOWHITE = RGB(100, 87, 67)
NAVY = RGB(0, 0, 50)
OLDLACE = RGB(99, 96, 90)
OLIVE = RGB(50, 50, 0)
OLIVEDRAB = RGB(41, 55, 13)
ORANGE = RGB(100, 50, 0)
ORANGERED = RGB(100, 27, 0)
ORCHID = RGB(85, 43, 83)
PALEGOLDENROD = RGB(93, 90, 66)
PALEGREEN = RGB(59, 98, 59)
PALETURQUOISE = RGB(73, 100, 100)
PALEVIOLETRED = RGB(85, 43, 57)
PAPAYAWHIP = RGB(100, 93, 83)
PEACHPUFF = RGB(100, 85, 72)
PEACOCK = RGB(20, 63, 78)
PINK = RGB(100, 75, 79)
PLUM = RGB(86, 62, 86)
POWDERBLUE = RGB(69, 87, 90)
PURPLE = RGB(50, 0, 50)
RASPBERRY = RGB(52, 14, 34)
RAWSIENNA = RGB(78, 38, 7)
RED = RGB(100, 0, 0)
ROSYBROWN = RGB(73, 56, 56)
ROYALBLUE = RGB(25, 41, 88)
SALMON = RGB(98, 50, 44)
SANDYBROWN = RGB(95, 64, 37)
SAPGREEN = RGB(18, 50, 7)
SEAGREEN = RGB(32, 100, 62)
SEASHELL = RGB(100, 96, 93)
SEPIA = RGB(36, 14, 7)
SGIBEET = RGB(55, 21, 55)
SGIBRIGHTGRAY = RGB(77, 75, 66)
SGICHARTREUSE = RGB(44, 77, 44)
SGIDARKGRAY = RGB(33, 33, 33)
SGILIGHTBLUE = RGB(49, 61, 75)
SGILIGHTGRAY = RGB(66, 66, 66)
SGIOLIVEDRAB = RGB(55, 55, 21)
SGISALMON = RGB(77, 44, 44)
SGISLATEBLUE = RGB(44, 44, 77)
SGITEAL = RGB(21, 55, 55)
SIENNA = RGB(62, 32, 17)
SILVER = RGB(75, 75, 75)
SKYBLUE = RGB(52, 80, 92)
SLATEBLUE = RGB(41, 35, 80)
SLATEGRAY = RGB(43, 50, 56)
SNOW = RGB(100, 98, 98)
SPRINGGREEN = RGB(0, 100, 49)
STEELBLUE = RGB(27, 50, 70)
TAN = RGB(82, 70, 54)
TEAL = RGB(0, 50, 50)
THISTLE = RGB(84, 74, 84)
TOMATO = RGB(100, 38, 27)
TURQUOISE = RGB(25, 87, 81)
TURQUOISEBLUE = RGB(0, 78, 54)
VIOLET = RGB(93, 50, 93)
VIOLETRED = RGB(81, 12, 56)
WARMGREY = RGB(50, 50, 41)
WHEAT = RGB(96, 87, 70)
WHITE = RGB(100, 100, 100)
WHITESMOKE = RGB(96, 96, 96)
YELLOW = RGB(100, 100, 0)

#Add colors to colors dictionary
colors['aliceblue'] = ALICEBLUE
colors['antiquewhite'] = ANTIQUEWHITE
colors['aqua'] = AQUA
colors['aquamarine'] = AQUAMARINE
colors['azure'] = AZURE
colors['banana'] = BANANA
colors['beige'] = BEIGE
colors['bisque'] = BISQUE
colors['black'] = BLACK
colors['blanchedalmond'] = BLANCHEDALMOND
colors['blue'] = BLUE
colors['blueviolet'] = BLUEVIOLET
colors['brick'] = BRICK
colors['brown'] = BROWN
colors['burlywood'] = BURLYWOOD
colors['burntsienna'] = BURNTSIENNA
colors['burntumber'] = BURNTUMBER
colors['cadetblue'] = CADETBLUE
colors['cadmiumorange'] = CADMIUMORANGE
colors['cadmiumyellow'] = CADMIUMYELLOW
colors['carrot'] = CARROT
colors['chartreuse'] = CHARTREUSE
colors['chocolate'] = CHOCOLATE
colors['cobalt'] = COBALT
colors['cobaltgreen'] = COBALTGREEN
colors['coldgrey'] = COLDGREY
colors['coral'] = CORAL
colors['cornflowerblue'] = CORNFLOWERBLUE
colors['cornsilk'] = CORNSILK
colors['crimson'] = CRIMSON
colors['cyan'] = CYAN
colors['darkgoldenrod'] = DARKGOLDENROD
colors['darkgray'] = DARKGRAY
colors['darkgreen'] = DARKGREEN
colors['darkkhaki'] = DARKKHAKI
colors['darkolivegreen'] = DARKOLIVEGREEN
colors['darkorange'] = DARKORANGE
colors['darkorchid'] = DARKORCHID
colors['darksalmon'] = DARKSALMON
colors['darkseagreen'] = DARKSEAGREEN
colors['darkslateblue'] = DARKSLATEBLUE
colors['darkslategray'] = DARKSLATEGRAY
colors['darkturquoise'] = DARKTURQUOISE
colors['darkviolet'] = DARKVIOLET
colors['deeppink'] = DEEPPINK
colors['deepskyblue'] = DEEPSKYBLUE
colors['dimgray'] = DIMGRAY
colors['dimgray'] = DIMGRAY
colors['dodgerblue'] = DODGERBLUE
colors['eggshell'] = EGGSHELL
colors['emeraldgreen'] = EMERALDGREEN
colors['firebrick'] = FIREBRICK
colors['flesh'] = FLESH
colors['floralwhite'] = FLORALWHITE
colors['forestgreen'] = FORESTGREEN
colors['gainsboro'] = GAINSBORO
colors['ghostwhite'] = GHOSTWHITE
colors['gold'] = GOLD
colors['goldenrod'] = GOLDENROD
colors['gray'] = GRAY
colors['green'] = GREEN
colors['greenyellow'] = GREENYELLOW
colors['honeydew'] = HONEYDEW
colors['hotpink'] = HOTPINK
colors['indianred'] = INDIANRED
colors['indigo'] = INDIGO
colors['ivory'] = IVORY
colors['ivoryblack'] = IVORYBLACK
colors['khaki'] = KHAKI
colors['lavender'] = LAVENDER
colors['lavenderblush'] = LAVENDERBLUSH
colors['lawngreen'] = LAWNGREEN
colors['lemonchiffon'] = LEMONCHIFFON
colors['lightblue'] = LIGHTBLUE
colors['lightcoral'] = LIGHTCORAL
colors['lightcyan'] = LIGHTCYAN
colors['lightgoldenrod'] = LIGHTGOLDENROD
colors['lightgoldenrodyellow'] = LIGHTGOLDENRODYELLOW
colors['lightgrey'] = LIGHTGREY
colors['lightpink'] = LIGHTPINK
colors['lightsalmon'] = LIGHTSALMON
colors['lightseagreen'] = LIGHTSEAGREEN
colors['lightskyblue'] = LIGHTSKYBLUE
colors['lightslateblue'] = LIGHTSLATEBLUE
colors['lightslategray'] = LIGHTSLATEGRAY
colors['lightsteelblue'] = LIGHTSTEELBLUE
colors['lightyellow'] = LIGHTYELLOW
colors['limegreen'] = LIMEGREEN
colors['linen'] = LINEN
colors['magenta'] = MAGENTA
colors['manganeseblue'] = MANGANESEBLUE
colors['maroon'] = MAROON
colors['mediumorchid'] = MEDIUMORCHID
colors['mediumpurple'] = MEDIUMPURPLE
colors['mediumseagreen'] = MEDIUMSEAGREEN
colors['mediumslateblue'] = MEDIUMSLATEBLUE
colors['mediumspringgreen'] = MEDIUMSPRINGGREEN
colors['mediumturquoise'] = MEDIUMTURQUOISE
colors['mediumvioletred'] = MEDIUMVIOLETRED
colors['melon'] = MELON
colors['midnightblue'] = MIDNIGHTBLUE
colors['mint'] = MINT
colors['mintcream'] = MINTCREAM
colors['mistyrose'] = MISTYROSE
colors['moccasin'] = MOCCASIN
colors['navajowhite'] = NAVAJOWHITE
colors['navy'] = NAVY
colors['oldlace'] = OLDLACE
colors['olive'] = OLIVE
colors['olivedrab'] = OLIVEDRAB
colors['orange'] = ORANGE
colors['orangered'] = ORANGERED
colors['orchid'] = ORCHID
colors['palegoldenrod'] = PALEGOLDENROD
colors['palegreen'] = PALEGREEN
colors['paleturquoise'] = PALETURQUOISE
colors['palevioletred'] = PALEVIOLETRED
colors['papayawhip'] = PAPAYAWHIP
colors['peachpuff'] = PEACHPUFF
colors['peacock'] = PEACOCK
colors['pink'] = PINK
colors['plum'] = PLUM
colors['powderblue'] = POWDERBLUE
colors['purple'] = PURPLE
colors['raspberry'] = RASPBERRY
colors['rawsienna'] = RAWSIENNA
colors['red'] = RED
colors['rosybrown'] = ROSYBROWN
colors['royalblue'] = ROYALBLUE
colors['salmon'] = SALMON
colors['sandybrown'] = SANDYBROWN
colors['sapgreen'] = SAPGREEN
colors['seagreen'] = SEAGREEN
colors['seashell'] = SEASHELL
colors['sepia'] = SEPIA
colors['sgibeet'] = SGIBEET
colors['sgibrightgray'] = SGIBRIGHTGRAY
colors['sgichartreuse'] = SGICHARTREUSE
colors['sgidarkgray'] = SGIDARKGRAY
colors['sgilightblue'] = SGILIGHTBLUE
colors['sgilightgray'] = SGILIGHTGRAY
colors['sgiolivedrab'] = SGIOLIVEDRAB
colors['sgisalmon'] = SGISALMON
colors['sgislateblue'] = SGISLATEBLUE
colors['sgiteal'] = SGITEAL
colors['sienna'] = SIENNA
colors['silver'] = SILVER
colors['skyblue'] = SKYBLUE
colors['slateblue'] = SLATEBLUE
colors['slategray'] = SLATEGRAY
colors['snow'] = SNOW
colors['springgreen'] = SPRINGGREEN
colors['steelblue'] = STEELBLUE
colors['tan'] = TAN
colors['teal'] = TEAL
colors['thistle'] = THISTLE
colors['tomato'] = TOMATO
colors['turquoise'] = TURQUOISE
colors['turquoiseblue'] = TURQUOISEBLUE
colors['violet'] = VIOLET
colors['violetred'] = VIOLETRED
colors['warmgrey'] = WARMGREY
colors['wheat'] = WHEAT
colors['white'] = WHITE
colors['whitesmoke'] = WHITESMOKE
colors['yellow'] = YELLOW

colors = OrderedDict(sorted(colors.items(), key=lambda t: t[0]))
